### PR TITLE
Custom widgets for cells

### PR DESCRIPTION
**Pull request by ASGAlex**
The grid is awesome, but it has a lack of functionality: it works only with texts and can not diaplay more complex data.
For example, my rest api returns me user profiles with avatars, so I have url string but i shouldn't show actually strings im my table. 

cTcy6JyOP7

this is example of expected behavior. 

Such widgets should not be editable, at least this behavior should not be handled by the grid.

Example, how this works on application side:
```
PlutoColumnType.widget(widget: (dynamic value) {
  if (value != null) {
    return Image.network(value, fit: BoxFit.scaleDown);
  }
  return Icon(Icons.image_not_supported_outlined);
})
```
Of couse, displaying user's images is not only one potentional use-case.

My solution still is a bit tricky, because class _CustomCellWidgetState extends directly _DefaultCellWidgetState instead State<CustomCellWidget>. I think, it should be fixed by converting a part of _DefaultCellWidgetState into mixin to share it's functionality.

### CODE REVIEW

**Comment by bosskmk** [comment]
Thanks for the first contribution. Let me apply this.

**Comment by bosskmk** [comment]
I've been thinking for a long time whether or not to add the CustomeWidget you suggested.

I have added enableEditingMode to the PlutoColumn property.
If you set enableEditingMode to false and have the renderer return an Image widget, I think this might be similar to what you want.
Added to version 1.0.0-pre.5.

I didn't merge your PR, but it helped me a lot.
Previous PRs have also helped a lot. Thank you again.

P.s. I want to add your profile to Contributors at the bottom of the Demo page.

**Comment by ASGAlex** [comment]
Great news! I've just checked new beta and I think that it's implementation is much better than my PR.  But I often prefer to show an example of solution than just leave an issue with feature request and no code at all :-) 

P.s. about my profile in Contributors - thanks, it would be nice!

**Comment by SteveBraich** [comment]
Does someone have a complete example of fitting or scaling a an image to fit within a PlutoCell?

**Pull request closed without merging**
