### PR TITLE
Added Brazilian Portuguese and Spanish translation

### PR DESCRIPTION
**Pull request by h3nr1ke**

### CODE REVIEW

**Comment by bosskmk** [comment]
Thank you for your contribution.
I saw this with google translate.
I will include it in the next version, 2.4.0.

**Comment by bosskmk** [comment]
@h3nr1ke 
A word has changed and translation is required.
Can you help?
https://www.reddit.com/r/flutterhelp/comments/vsj7jc/i_need_translation_help_from_the_open_source/

**Comment by h3nr1ke** [comment]
Hello @henry2man an @bosskmk 

I think that the translations are correct, also commented inside Redditś thread =) 

thanks for all the effort to keep this updated =)

**Comment by h3nr1ke** [comment]
Also did a [PR](https://github.com/bosskmk/pluto_grid/pull/487) to this

**Pull request merged**
