### PR TITLE
Support RTL and add Arabic locale

### LINKED ISSUE #260: working in RTL languages like Hebrew and Arabic
how can i configure RTL  ?

### PR DESCRIPTION
**Pull request by MajedDH**
This fixes #260 

My friend here, Mohamed, fixed a bug that appears when resizing a column in a RTL app. also there was a problem with aligning the columns icon, it supported right/left only, they supported start/end too. and moving cells using arrows now works properly

Farouk added Arabic locale to the grid too. 

Also, They've coded a way to allow users of the grid to save the order of columns (so it's restored when the app is restarted), that's convenient to the end-user. I know it shouldn't be on this pull request, so we can revert it, or refactor it to be more clean, whatever convenient.

### CODE REVIEW

**Comment by bosskmk** [comment]
Thanks for implementing the necessary features for RTL users.

I am checking it because it seems to have an effect on the existing operation.

**Comment by bosskmk** [comment]
@MajedDH 
hello.
In Flutter 3.0, TextField seems to support RTL automatically.
Can you tell me how the UI should change in an environment that uses RTL like Arabic?

For example, should the order of the columns be right-to-left rather than left-to-right?

If you tell us the function that needs to be changed, we will refer to your code and update it to match the 3.0 version.

thank you.

**Comment by MajedDH** [comment]
Yeah, the columns should be reversed ( first column on right) and even the icons 
If you have leading/tailing icons it'll be reversed too. 
text alignment should be reversed too (in this pull request it's been set to start, so flutter can handle left/right)  

I considered that when I fixed the resize performance. in the other pull request. you can see that when you open an rtl project.

**Comment by bosskmk** [comment]
@MajedDH 
RTL has been developed with reference to your code.

I'm attaching a link so you can preview it before deploying.

can you please confirm?

https://weblaze.dev/pluto_grid/build/pre/web/#feature/rtl

**Comment by MajedDH** [comment]
Sorry for the delay, I'm really tight on time these days
The RTL in the site Looks legit! don't forget to merge the localizations too

**Comment by henry2man** [comment]
Save grid setup feature will be merged here? This will be super nice 👍

**Comment by hamzaj9** [comment]
@bosskmk Kindly add rtl to the next update. i want to try it

**Comment by bosskmk** [comment]
@hamzaj9 

Yes, I tried to update this feature, but there was a bit of a problem.

I will try adding the feature again.

This is a feature I definitely want to add.

However, since I do not know how the Arabic language works, it cannot be verified that the overall operation is correct, so even if the function is developed, it cannot be distributed.

I will try again referring to this PR.

**Comment by MajedDH** [comment]
@bosskmk  RTL support in the link you shared looks good to go with. what questions do you have about it before you can distribute it ? maybe I can help.

**Comment by bosskmk** [comment]
@MajedDH 
The RTL demo link above should be rechecked in the Develop branch now.
I am currently in the process of developing and testing the functions that will go into version 4.1.
I'll check out the RTL functionality again when this is over.
At that time, if I have any questions during development, I will ask for help.

**Comment by hamzaj9** [comment]
@bosskmk okay, thats good. do you know when you will release 4.1?

**Comment by bosskmk** [comment]
@hamzaj9 
4.1 is almost done.
I also do RTL work from time to time.

**Comment by bosskmk** [comment]
@hamzaj9 
A word has changed and translation is required.
Can you help?
https://www.reddit.com/r/flutterhelp/comments/vsj7jc/i_need_translation_help_from_the_open_source/

**Comment by MajedDH** [comment]
@bosskmk  I don't have a reddit account , so here:

Freeze to start - تجميد إلى البداية

Freeze to end - تجميد إلى النهاية

**Comment by bosskmk** [comment]
@MajedDH 
@hamzaj9 
I've done some RTL.
I need help testing if I can deploy it.

The current version has some bugs.
When applying AutoSize dynamically programmatically, sometimes some columns or cells are not shown.
I think I know where the problem is. As the structural problems are improved, the corresponding bugs will also be fixed.
No other issues have been found yet.

https://weblaze.dev/pluto_grid/build/pre/web/#development
You can select TextDirection from the header Internationalization menu.


https://weblaze.dev/pluto_grid/build/pre/web/#feature/rtl
Demo page with only RTL examples.

**Comment by MajedDH** [comment]
Currently we're using this branch (support_rtl) and there is no problem regarding the autofit programmatically. I know there are lots of changes from then, but maybe if you can help me replicate the issue on the develop branch I can repair it, we'll have to anyway 😄

**Comment by bosskmk** [comment]
@MajedDH 
Currently found AutoSize issues.

reproduction step.
1. Access https://weblaze.dev/pluto_grid/build/pre/web/#development page
2. Move the horizontal scroll by dragging the mouse from the right edge to the left edge.
3. Click the equal or scale radio button in the top Size menu.

Benefit.
All visible cells and columns should be displayed on the screen.

test results.
Some cells and columns on the right do not appear.

Probable problem points. (It's still being checked, so I'm not sure.)
Failed to detect changes in newly added /ui/miscellaneous/pluto_visibility_layout.dart .
It seems that the existing width is not changed, so the update is not possible.

```dart
  void scrollListener() {
    final bool sameBoundScroll = _lastVisibleStartX1 <= visibleLeft &&
        visibleLeft <= _lastVisibleStartX2 &&
        _lastVisibleEndX1 <= visibleRight &&
        visibleRight <= _lastVisibleEndX2;

    if (sameBoundScroll &&
        _lastMaxScroll == scrollController.position.maxScrollExtent) {
      return;
    }

    _lastMaxScroll = scrollController.position.maxScrollExtent;

    markNeedsBuild();
  }
```

**Comment by bosskmk** [comment]
Also, when moving the current scroll to the right, PlutoGrid, PlutoBodyColumns, PlutoBodyRows, etc. seem to operate unnecessary performLayout.
Perhaps because of this, the average ms of the Raster thread is high.
I'm still learning flutter, so I didn't take these issues into account during development.

**Comment by bosskmk** [comment]
@MajedDH 
@hamzaj9 
I am writing test code.
While checking the RTL operation of other grids, I found that the keyboard operation of all other grids moved to the right when the right arrow key was used.
Is this correct?
Then I have to redevelop the keyboard, tab, Home, End key behavior etc.

**Comment by bosskmk** [comment]
> @MajedDH Currently found AutoSize issues.
> 
> reproduction step.
> 
> 1. Access https://weblaze.dev/pluto_grid/build/pre/web/#development page
> 2. Move the horizontal scroll by dragging the mouse from the right edge to the left edge.
> 3. Click the equal or scale radio button in the top Size menu.
> 
> Benefit. All visible cells and columns should be displayed on the screen.
> 
> test results. Some cells and columns on the right do not appear.
> 
> Probable problem points. (It's still being checked, so I'm not sure.) Failed to detect changes in newly added /ui/miscellaneous/pluto_visibility_layout.dart . It seems that the existing width is not changed, so the update is not possible.
> 
> ```dart
>   void scrollListener() {
>     final bool sameBoundScroll = _lastVisibleStartX1 <= visibleLeft &&
>         visibleLeft <= _lastVisibleStartX2 &&
>         _lastVisibleEndX1 <= visibleRight &&
>         visibleRight <= _lastVisibleEndX2;
> 
>     if (sameBoundScroll &&
>         _lastMaxScroll == scrollController.position.maxScrollExtent) {
>       return;
>     }
> 
>     _lastMaxScroll = scrollController.position.maxScrollExtent;
> 
>     markNeedsBuild();
>   }
> ```

I found the problem.
Structural improvements need to be made.
Currently, the performRebuild step of pluto_visibility_layout.dart determines what is visible on the screen and builds it.

I think this should be done Lazy build in the performLayout step.

And update viewportDimension and contentDimension of scroll when performLayout is finished.

**Pull request closed without merging**
