### PR TITLE
Partial or maybe full fix of #537

### PR DESCRIPTION
**Pull request by Macacoazul01**
this pull request fixes the initstate when `widget.mode.isSelect = true`

Fixes issue: #537

### CODE REVIEW

**Comment by Macacoazul01** [comment]
@bosskmk any chances of this being included in 5.1 or a hotfix 5.0.5?

**Comment by bosskmk** [comment]
It will be added in version 5.0.5.
I've been busy with other things lately and haven't been paying attention to this project.
I will update soon.
thank you

**Comment by Macacoazul01** [comment]
Any date for the release of this fix?

**Comment by bosskmk** [comment]
Updated to PlutoGrid 5.0.5.
Thanks for the code contribution.

**Pull request merged**
