### PR TITLE
Added optional border radius

### PR DESCRIPTION
**Pull request by christianarduino**
Once this change has been merged, it will be possible to add borderRadius to the entire table or not

### CODE REVIEW

**Comment by bosskmk** [comment]
I'll apply a few fixes and merge them.
Thank you for your contribution.

**Comment by bosskmk** [comment]
The method of applying the background color of the row is applied in the getter method.
https://www.ag-grid.com/javascript-data-grid/row-styles/

**Comment by bosskmk** [comment]
https://github.com/bosskmk/pluto_grid/tree/christianarduino-master

3101bd7d - Move borderRadius from grid constructor to configuration .
c07d2a15 - Added text center alignment.
15a83140 - Update column text align.

**Comment by christianarduino** [comment]
> The method of applying the background color of the row is applied in the getter method. https://www.ag-grid.com/javascript-data-grid/row-styles/

I didn't understand how to apply it to the widget on Flutter. Can you give an example?

**Comment by bosskmk** [comment]
@christianarduino 
I think my comment was mistranslated using a translator.
I want to change the way I change the background color in a similar way to the link.
I'm working on it and I plan to merge it into develop and release it.
I have other fixes as well and plan to add them in the next version with your work when they are done.
thank you.

**Comment by bosskmk** [comment]
@christianarduino 
I've merged some fixes along with your work into the develop branch.
Feel free to check it out and give your comments.

**Comment by bosskmk** [comment]
@christianarduino 
In addition, and thank you very much for your contribution.
I haven't been paying attention to this lately because I've been concentrating on something else, but your contribution has been added again, and in the meantime, an error has been found and is being fixed.

**Comment by jlnrrg** [comment]
@bosskmk very usefull new feature, additionally it might lead to a more consistent look, if the borderRadius for the popUps can also be set :thinking:

**Comment by bosskmk** [comment]
@jlnrrg 
I will modify the borderRadius to be reflected in the popup as well.

**Pull request merged**
