### PR TITLE
support sticky footers for columns

### LINKED ISSUE #289: Add support for a totalizer bottom row always visible on a table
This would be an awesome feature, is there ever going to be support for it? Thanks!

### PR DESCRIPTION
**Pull request by MajedDH**
This should close #289

### CODE REVIEW

**Comment by MajedDH** [comment]
@bosskmk   FYI: during the development the visibility layout was buggy (maybe something related to the `visible` method? ) I tried to debug it but couldn't solve the issue. horizontal scrolling was causing errors (maybe elements were mounted without their widgets, or the opposite... I don't know exactly) 
So temporarily I used `keepAlive=true` on all the classes that use visibility layout child 😅, I kept it that way for the columns and footers, only cells now have `keepAlive` as is. I don't think it'll affect performance, it is neglectable for the headers/footers. but important for the cells.  

Should I create a detailed issue for that or you know what's the problem is already?

**Comment by bosskmk** [comment]
I'll get the code and run it to see what the problem you are referring to is.

You have implemented a nice feature. Genius.

**Comment by MajedDH** [comment]
> I'll get the code and run it to see what the problem you are referring to is.
> 
> You have implemented a nice feature. Genius.

I'll mail you a video showing the issue

**Comment by yingming25** [comment]
@MajedDH hi~
Thank you contribution.
Has the problem been solved?

**Comment by MajedDH** [comment]
Hi! 
@yingming25 
I've totally forgot about it . 🥲 
I don't know if it's been solved. but locally to solve the issue I disabled the visibilitylayout. 

@bosskmk I think this PR isn't related to the problem I've mentioned. can you consider merging it ?

**Comment by bosskmk** [comment]
@MajedDH 
There is a bug that the keyboard and scroll behavior should be fixed.
I will update this to version 5.1.0 after fixing it.

**Pull request merged**
