### PR TITLE
Feat on col moved evt

### PR DESCRIPTION
**Pull request by Hu-Wentao**

### CODE REVIEW

**Comment by bosskmk** [comment]
@Hu-Wentao 
Thanks for the code contribution.

I have one question.

In what situations is the column width change event used?

**Comment by robertjones1** [comment]
Will this feature be added soon?

**Comment by bosskmk** [comment]
@robertjones1 
Waiting for @Hu-Wentao 's reply.
If there is no answer, it will be added except for the column width change event.

**Comment by Hu-Wentao** [comment]
In some online collaborative spreadsheet applications, users need the table to maintain their modified column width for viewing by other users or themselves.

**Pull request closed without merging**
